### ISSUE TITLE
Game Concept: Survival

### ISSUE THREAD

**Issue by Nerriz** [Nerriz/gameOff#3]
The base code does not have to be fully created in unity. You can just link a blog or a video tutorial. 

Ehnel GDD

- [ ]  Game Mechanics
- [ ]  Concept art (moodboard)
- [ ]  Base code 

EJ GDD

- [ ]  Game Mechanics
- [ ]  Concept art (moodboard)
- [ ]  Base code

**Comment by ejmal18** [comment]
Game Design Document

Moon Theme/Rogue like survival game

Overview
The game will be a survival horror game in space where players must survive waves of dangerous alien zygotes from the dark side of the moon that attack their moon space station. Players will have to strategies on defences and how they can survive each wave without getting overrun. Players can create their weapons on a workbench inside the space station, there are also defence mechanism that can be repaired in the game that will add some advantages on the players end.


Story


Gameplay
The game will have numerous options for the player to survive through out the waves. One of the first mechanics that the player will encounter is the repairable terrain, The player is able to repair windows and doors which takes a bit of time to be fully repaired and once that’s repaired it can block the enemies from entering the building as well as the enemy has to destroy the door which will take some time as well. The next mechanic is the upgrading/crafting mechanic where the player can create weapons that the monsters drop and use them to either upgrade or create weapons to help them fight off the waves.

Genre
The genre of the game will be a horror based, because it fits the aesthetic of a survival game in space.

Target Audience
Target audience will vary but the main target is 16 and up because it will have a bit of blood and gore.


Team Members
Project Lead: EJ G
Lead Programmer: Miguel
Assistant Designer: Ehnel, EJ B
Programmer: EJ B

**Comment by TooDamnFluffy** [comment]
https://drive.google.com/file/d/1Hz5Tbf09H7PNBJTK0fdzrTsMcfVjRCBY/view?usp=sharing
